//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiOnline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_thitinhocEntities : DbContext
    {
        public db_thitinhocEntities()
            : base("name=db_thitinhocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_cauhoi> tbl_cauhoi { get; set; }
        public virtual DbSet<tbl_chitiet_phieulambai> tbl_chitiet_phieulambai { get; set; }
        public virtual DbSet<tbl_danhsachthi> tbl_danhsachthi { get; set; }
        public virtual DbSet<tbl_dethi> tbl_dethi { get; set; }
        public virtual DbSet<tbl_dethi_cauhoi> tbl_dethi_cauhoi { get; set; }
        public virtual DbSet<tbl_dotthi> tbl_dotthi { get; set; }
        public virtual DbSet<tbl_ketquahoctap> tbl_ketquahoctap { get; set; }
        public virtual DbSet<tbl_lop> tbl_lop { get; set; }
        public virtual DbSet<tbl_mail> tbl_mail { get; set; }
        public virtual DbSet<tbl_mucdocauhoi> tbl_mucdocauhoi { get; set; }
        public virtual DbSet<tbl_phieulambai> tbl_phieulambai { get; set; }
        public virtual DbSet<tbl_phuongan> tbl_phuongan { get; set; }
        public virtual DbSet<tbl_sinhvien> tbl_sinhvien { get; set; }
        public virtual DbSet<tbl_thanhvien> tbl_thanhvien { get; set; }
    }
}
