//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cauhoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_cauhoi()
        {
            this.tbl_dethi_cauhoi = new HashSet<tbl_dethi_cauhoi>();
            this.tbl_phuongan = new HashSet<tbl_phuongan>();
        }
    
        public int MaCauHoi { get; set; }
        public string CauHoi { get; set; }
        public string HinhAnh { get; set; }
        public string GhiChu { get; set; }
        public string MaKQHT { get; set; }
        public int MaMucDoCauHoi { get; set; }
    
        public virtual tbl_ketquahoctap tbl_ketquahoctap { get; set; }
        public virtual tbl_mucdocauhoi tbl_mucdocauhoi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_dethi_cauhoi> tbl_dethi_cauhoi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_phuongan> tbl_phuongan { get; set; }
    }
}
