//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_chitiet_phieulambai
    {
        public int MaDeThiCauHoi { get; set; }
        public int MaPhieu { get; set; }
        public int PhuongAnChon { get; set; }
    
        public virtual tbl_dethi_cauhoi tbl_dethi_cauhoi { get; set; }
        public virtual tbl_phieulambai tbl_phieulambai { get; set; }
    }
}
