//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_dethi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_dethi()
        {
            this.tbl_dethi_cauhoi = new HashSet<tbl_dethi_cauhoi>();
        }
    
        public string MaDeThi { get; set; }
        public string TenDeThi { get; set; }
        public string MaCaThi { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayThi { get; set; }
        public int TrangThai { get; set; }
        public string MaGiangVien { get; set; }
        public string MaDotThi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_dethi_cauhoi> tbl_dethi_cauhoi { get; set; }
        public virtual tbl_dotthi tbl_dotthi { get; set; }
        public virtual tbl_thanhvien tbl_thanhvien { get; set; }
    }
}
