//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_phuongan
    {
        public int MaPhuongAn { get; set; }
        public string PhuongAn { get; set; }
        public string HinhAnh { get; set; }
        public int TrangThai { get; set; }
        public int MaCauHoi { get; set; }
    
        public virtual tbl_cauhoi tbl_cauhoi { get; set; }
    }
}
