//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_dethi_cauhoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_dethi_cauhoi()
        {
            this.tbl_chitiet_phieulambai = new HashSet<tbl_chitiet_phieulambai>();
        }
    
        public int MaDeThiCauHoi { get; set; }
        public string MaDeThi { get; set; }
        public int MaCauHoi { get; set; }
    
        public virtual tbl_cauhoi tbl_cauhoi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_chitiet_phieulambai> tbl_chitiet_phieulambai { get; set; }
        public virtual tbl_dethi tbl_dethi { get; set; }
    }
}
