//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_danhsachthi
    {
        public int Ma { get; set; }
        public string MaDotThi { get; set; }
        public string MaSinhVien { get; set; }
    
        public virtual tbl_dotthi tbl_dotthi { get; set; }
        public virtual tbl_sinhvien tbl_sinhvien { get; set; }
    }
}
